# Generated by Django 3.2.6 on 2021-11-06 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_type',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_id',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
