# Generated by Django 3.2.6 on 2021-11-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211106_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razor_payment_id',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='razor_signature_id',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
