# Generated by Django 3.2.6 on 2021-11-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211108_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_address',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_name',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
