# Generated by Django 3.2.6 on 2021-11-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211110_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url_hex',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
