# Generated by Django 3.2.6 on 2021-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_aibeing'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('noti_type', models.TextField()),
                ('noti_id', models.BigIntegerField()),
                ('customer_id', models.BigIntegerField()),
                ('customer_access', models.TextField()),
                ('noti_status', models.TextField()),
                ('noti_ringtone', models.TextField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
    ]
