# Generated by Django 3.2.6 on 2021-12-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('offer_id', models.BigIntegerField()),
                ('customer_id', models.BigIntegerField()),
                ('customer_access', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='offer_percentage_amount',
            field=models.BigIntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='offer_percentage_amount',
            field=models.BigIntegerField(default=int),
            preserve_default=False,
        ),
    ]
