# Generated by Django 3.2.6 on 2021-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
    ]
