# Generated by Django 3.2.6 on 2021-09-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('bannername', models.TextField()),
                ('banner_order', models.IntegerField()),
                ('banner_image', models.TextField()),
                ('banner_link', models.TextField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='cat_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('cat_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('name', models.TextField()),
                ('order', models.IntegerField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('name', models.TextField()),
                ('email_id', models.TextField()),
                ('address', models.TextField()),
                ('gst', models.TextField()),
                ('phone', models.TextField()),
                ('file', models.TextField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='food_catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('name', models.TextField()),
                ('dish_image', models.TextField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('code', models.TextField()),
                ('itemname', models.TextField()),
                ('itemimage', models.TextField()),
                ('rate', models.BigIntegerField()),
                ('discount', models.IntegerField()),
                ('dish_cat', models.IntegerField()),
                ('food_cat', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('stock_alert', models.IntegerField()),
                ('sales_status', models.IntegerField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField()),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('status', models.TextField()),
                ('last_change', models.DateTimeField()),
            ],
        ),
    ]
